baseURL = "https://adityatelange.github.io/hugo-PaperMod/"
title = "PaperMod"
author = "Steve Francia"
copyright = "Copyright © 2008–2019, Steve Francia and the Hugo Authors; all rights reserved."
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "hugo-PaperMod"

[params]
  description = "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
  author = "Theme PaperMod"
  ShowReadingTime = true
  SetThemeAuto = true
  contentTypeName = "posts"
  defaultTheme = "auto"
  ShowShareButtons = true

  [params.profileMode]
  enabled = false
  title = "PaperMod"
  imageUrl = "#"
  imageTitle = "my image"

  [[params.profileMode.buttons]]
  name = "Archives"
  url = "archives"

  [[params.profileMode.buttons]]
  name = "Tags"
  url = "tags"

  [params.homeInfoParams]
    Title = "Hi there 👋"
    Content = "Welcome to my blog"

  [[params.socialIcons]]
  name = "twitter"
  url = "#"

  [[params.socialIcons]]
  name = "stackoverflow"
  url = "#"

  [[params.socialIcons]]
  name = "codepen"
  url = "#"

  [[params.socialIcons]]
  name = "linkedin"
  url = "#"

  [[params.socialIcons]]
  name = "github"
  url = "#"

[menu]

  [[menu.main]]
    name = "Archives"
    url = "archives/"
    weight = 5

  [[menu.main]]
    name = "Tags"
    url = "tags/"
    weight = 10

  [[menu.main]]
    name = "Series"
    url = "series/"
    weight = 15

  [[menu.main]]
    name = "Categories"
    url = "categories/"
    weight = 20

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
