baseURL: "https://adityatelange.github.io/hugo-PaperMod/"
title: PaperMod
paginate: 8
theme: hugo-PaperMod
enableInlineShortcodes: true

params:
  env: production
  description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
  author: Theme PaperMod
  ShowReadingTime: true
  defaultTheme: auto
  ShowShareButtons: true
  profileMode:
    enabled: false
    title: PaperMod
    imageUrl: "#"
    imageTitle: my image
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags

  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: twitter
      url: "#"
    - name: stackoverflow
      url: "#"
    - name: codepen
      url: "#"
    - name: linkedin
      url: "#"
    - name: github
      url: "https://github.com/adityatelange/hugo-PaperMod"

menu:
  main:
    - name: Archives
      url: /archives/
      weight: 5
    - name: Tags
      url: /tags/
      weight: 10

taxonomies:
  category: categories
  tag: tags
  series: series

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
