baseURL = "https://adityatelange.github.io/hugo-PaperMod/"
title = "PaperMod"
author = "Steve Francia"
copyright = "Copyright © 2008–2019, Steve Francia and the Hugo Authors; all rights reserved."
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "hugo-PaperMod"

[params]
  [params.homeInfoParams]
    enabled = true
    Title = "Hi there 👋"
    Content = "This is Content !! Can be Info, links, social-icons..."

[menu]

  [[menu.main]]
    name = "Archives"
    url = "/archives/"
    weight = 5

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 10

  [[menu.main]]
    name = "Series"
    url = "/series/"
    weight = 15

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 20

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
